#!/usr/bin/env bash
roku-keypress(){
#Configure the keys for commands. 
declare -A commands
commands[m]=volumemute
commands[!]=volumemute
commands[\[]=keydown
commands[\]]=keyup
commands[o]=volumeup
commands[k]=volumedown
commands[h]=home
commands[\@]=home
commands[.]=enter
commands[s]=select
commands[_]=select
commands[<blank>]=select
commands["<space>"]=select
commands["<enter>"]=select
commands[e]=up
commands[{]=up
commands[x]=down
commands[}]=down
commands[a]=left
commands[<]=left
commands[l]=launch
commands[d]=right
commands[>]=right
commands[b]=back
commands[#]=back
commands['*']=info
commands[0]=backspace
commands[r]=rev
commands[f]=fwd
commands[p]=play
commands[i]="<Choose Roku>"
commands[v]="<enter some text>"

#Configure the Roku IP
[[ -f rokuip ]] && rn=$(cat rokuip) || rn="1.200"
ROKUIP="192.168.${rn}"

if [[  "$1" == '/' ]]; then clear
echo
for val in  "${!commands[@]}";do echo "${val} = ${commands[$val]}";done;return 0
elif [[ "$1" == 'i' ]]; then ./choose; return 0
elif [[ "$1" == 'v' ]]; then ./enter; return 0
elif [[ "$1" == 'l' ]]; then ./launch; return 0
elif [[ -n "$1"  ]]; then
#Otherwise, do the keypress. 
command="$1"
fi
URLBASE="http://${ROKUIP}:8060/key$2"
if [[ -n "$command" ]]; then
if [[ -n ${commands["$command"]} ]];then
#echo 
#echo $URLBASE/${commands["$command"]} >>rokontroller.log
curl -d '' $URLBASE/${commands["$command"]}
fi
fi
}

roku-keypress "$1" ${2:-press}

