#!/usr/bin/env bash

#Infinitely read for one character commands. 

while true
do
#Show all the commands at the beginning 
./keypress /
read -n 1 -p  'Enter a command: ' comm
[[ $comm == 'q' ]] && clear && exit 0
[[ $comm == ':' ]] && clear && exit 0

#A <space> or <enter> equals "select". 
if [[ -z $comm ]]; then ./keypress s press
elif [[ $comm == '[' ]]; then
echo
read -n 1 -p "Command to hold: " HELD
./keypress $HELD down
elif [[ $comm == ']' ]]; then
./keypress $HELD up
unset $HELD
else
./keypress "$comm" press
fi
done

