#!/usr/bin/env bash
roku-keypress(){
#ROKUIP="$(configure)"
declare -A commands
commands[m]=volumemute
commands[o]=volumeup
commands[k]=volumedown
commands[h]=home
commands[s]=select
commands["<blank>"]=select
commands[e]=up
commands[x]=down
commands[a]=left
commands[d]=right
commands[b]=back
commands[r]=rev
commands[f]=fwd
commands[p]=play
commands[<blank>]=select
commands[/]="<list commands>"
commands[<blank>]=select
commands[c]="configure roku address"

ROKUIP="<error>"
if [[ -e  ./roku-address ]] ;then
ROKUIP=$(cat ./roku-address)
elif [[ true ]];then
echo
echo "Config file doesn't exist."
while [ $ROKUIP == "<error>" ] || [ -z "$ROKUIP" ];do
echo "Enter the Roku IP: "
read ROKUIP
echo $ROKUIP>./roku-address
done
fi

if [[ -z $1 ]];then
command=s
elif [[  $1 == '/' ]];then
echo
for val in  ${!commands[@]};do echo "${val} = ${commands[$val]}";done;return 0
elif [[ $1 == 'q' ]];then exit 0
elif [[ $1 == 'c' ]];then 
ROKUIP="<error>"
while [ $ROKUIP == "<error>" ] || [ -z "$ROKUIP" ];do
echo
echo "Enter the Roku IP: "
read ROKUIP
echo $ROKUIP>./roku-address
done
elif [[ -n $1  ]]; then
command=$1
fi
URLBASE="http://${ROKUIP}:8060/keypress"
if [[ -n $command ]]; then
if [[ -n ${commands[$command]} ]];then
echo
echo $URLBASE/${commands[$command]}
curl -d '' $URLBASE/${commands[$command]}
fi
fi
}
roku-keypress /
while true
do
echo -n "Enter a command: "
read -n 1 comm
roku-keypress $comm
done